"""add user columns to maintenance

Revision ID: [autogenerated]
Revises: [previous revision]
Create Date: 2024-02-08

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '[autogenerated]'
down_revision = '[previous revision]'
branch_labels = None
depends_on = None

def upgrade():
    # Agregar columnas faltantes a la tabla maintenances
    op.add_column('maintenances', sa.Column('assigned_user_id', sa.Integer(), nullable=True))
    op.add_column('maintenances', sa.Column('assigned_role_id', sa.Integer(), nullable=True))
    op.add_column('maintenances', sa.Column('is_completed', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('maintenances', sa.Column('frequency', sa.String(), nullable=True))
    op.add_column('maintenances', sa.Column('notification_interval', sa.Integer(), nullable=True))
    op.add_column('maintenances', sa.Column('next_maintenance_date', sa.DateTime(), nullable=True))
    op.add_column('maintenances', sa.Column('last_maintenance_date', sa.DateTime(), nullable=True))
    
    # Crear las foreign keys
    op.create_foreign_key(
        'fk_maintenance_user',
        'maintenances', 'users',
        ['assigned_user_id'], ['id']
    )
    op.create_foreign_key(
        'fk_maintenance_role',
        'maintenances', 'roles',
        ['assigned_role_id'], ['id']
    )

def downgrade():
    # Eliminar las foreign keys primero
    op.drop_constraint('fk_maintenance_user', 'maintenances', type_='foreignkey')
    op.drop_constraint('fk_maintenance_role', 'maintenances', type_='foreignkey')
    
    # Luego eliminar las columnas
    op.drop_column('maintenances', 'last_maintenance_date')
    op.drop_column('maintenances', 'next_maintenance_date')
    op.drop_column('maintenances', 'notification_interval')
    op.drop_column('maintenances', 'frequency')
    op.drop_column('maintenances', 'is_completed')
    op.drop_column('maintenances', 'assigned_role_id')
    op.drop_column('maintenances', 'assigned_user_id')
