"""Add shift_overrides table

Revision ID: 1a8cf6de4961
Revises: eed6024e198c
Create Date: 2025-04-25 21:57:42.301848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a8cf6de4961'
down_revision: Union[str, None] = 'eed6024e198c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('actual_shift_pattern_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['actual_shift_pattern_id'], ['shift_patterns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_overrides_date'), 'shift_overrides', ['date'], unique=False)
    op.create_index(op.f('ix_shift_overrides_id'), 'shift_overrides', ['id'], unique=False)
    op.create_index(op.f('ix_shift_overrides_user_id'), 'shift_overrides', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shift_overrides_user_id'), table_name='shift_overrides')
    op.drop_index(op.f('ix_shift_overrides_id'), table_name='shift_overrides')
    op.drop_index(op.f('ix_shift_overrides_date'), table_name='shift_overrides')
    op.drop_table('shift_overrides')
    # ### end Alembic commands ###
