"""add_stock_minimo_to_inventory

Revision ID: 560c85bf6f60
Revises: 470b2e57ee0a
Create Date: 2025-04-27 10:32:54.333705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560c85bf6f60'
down_revision: Union[str, None] = '470b2e57ee0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('stock_minimo', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'stock_minimo')
    # ### end Alembic commands ###
