"""Add shift patterns, assignments, and absences tables

Revision ID: 6c53c777fae1
Revises: ecf598d45ac8
Create Date: 2025-04-23 13:45:54.969599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c53c777fae1'
down_revision: Union[str, None] = 'ecf598d45ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pattern_sequence', sa.String(), nullable=False),
    sa.Column('cycle_length_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_patterns_id'), 'shift_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_shift_patterns_name'), 'shift_patterns', ['name'], unique=True)
    op.create_table('absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('absence_type', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_absences_absence_type'), 'absences', ['absence_type'], unique=False)
    op.create_index(op.f('ix_absences_end_date'), 'absences', ['end_date'], unique=False)
    op.create_index(op.f('ix_absences_id'), 'absences', ['id'], unique=False)
    op.create_index(op.f('ix_absences_start_date'), 'absences', ['start_date'], unique=False)
    op.create_index(op.f('ix_absences_user_id'), 'absences', ['user_id'], unique=False)
    op.create_table('shift_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=False),
    sa.Column('offset_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['shift_patterns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_shift_assignments_id'), 'shift_assignments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shift_assignments_id'), table_name='shift_assignments')
    op.drop_table('shift_assignments')
    op.drop_index(op.f('ix_absences_user_id'), table_name='absences')
    op.drop_index(op.f('ix_absences_start_date'), table_name='absences')
    op.drop_index(op.f('ix_absences_id'), table_name='absences')
    op.drop_index(op.f('ix_absences_end_date'), table_name='absences')
    op.drop_index(op.f('ix_absences_absence_type'), table_name='absences')
    op.drop_table('absences')
    op.drop_index(op.f('ix_shift_patterns_name'), table_name='shift_patterns')
    op.drop_index(op.f('ix_shift_patterns_id'), table_name='shift_patterns')
    op.drop_table('shift_patterns')
    # ### end Alembic commands ###
