"""Add TaskList and TaskStep tables (Corrected)

Revision ID: 7fd98f1e6772
Revises: 3d345d9fa592
Create Date: 2025-04-22 16:54:49.769662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fd98f1e6772'
down_revision: Union[str, None] = '3d345d9fa592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('applies_to_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_lists_applies_to_type'), 'task_lists', ['applies_to_type'], unique=False)
    op.create_index(op.f('ix_task_lists_id'), 'task_lists', ['id'], unique=False)
    op.create_index(op.f('ix_task_lists_name'), 'task_lists', ['name'], unique=True)
    op.create_table('task_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_list_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_time_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_list_id'], ['task_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_steps_id'), 'task_steps', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_steps_id'), table_name='task_steps')
    op.drop_table('task_steps')
    op.drop_index(op.f('ix_task_lists_name'), table_name='task_lists')
    op.drop_index(op.f('ix_task_lists_id'), table_name='task_lists')
    op.drop_index(op.f('ix_task_lists_applies_to_type'), table_name='task_lists')
    op.drop_table('task_lists')
    # ### end Alembic commands ###
