"""Add vacation_requests table

Revision ID: ac833911eab4
Revises: b64510a3bc05
Create Date: 2025-04-26 13:30:40.936989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac833911eab4'
down_revision: Union[str, None] = 'b64510a3bc05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('Solicitado', 'Aprobado', 'Rechazado', name='vacation_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('manager_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacation_requests_end_date'), 'vacation_requests', ['end_date'], unique=False)
    op.create_index(op.f('ix_vacation_requests_id'), 'vacation_requests', ['id'], unique=False)
    op.create_index(op.f('ix_vacation_requests_start_date'), 'vacation_requests', ['start_date'], unique=False)
    op.create_index(op.f('ix_vacation_requests_status'), 'vacation_requests', ['status'], unique=False)
    op.create_index(op.f('ix_vacation_requests_user_id'), 'vacation_requests', ['user_id'], unique=False)
    op.alter_column('shift_overrides', 'actual_shift_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shift_overrides', 'actual_shift_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_index(op.f('ix_vacation_requests_user_id'), table_name='vacation_requests')
    op.drop_index(op.f('ix_vacation_requests_status'), table_name='vacation_requests')
    op.drop_index(op.f('ix_vacation_requests_start_date'), table_name='vacation_requests')
    op.drop_index(op.f('ix_vacation_requests_id'), table_name='vacation_requests')
    op.drop_index(op.f('ix_vacation_requests_end_date'), table_name='vacation_requests')
    op.drop_table('vacation_requests')
    # ### end Alembic commands ###
