"""Add shift_override table with shift_code

Revision ID: b64510a3bc05
Revises: 1a8cf6de4961
Create Date: 2025-04-26 07:18:02.577095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b64510a3bc05'
down_revision: Union[str, None] = '1a8cf6de4961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_overrides', sa.Column('actual_shift_code', sa.String(length=10), nullable=True)) # <<<--- ASEGÚRATE QUE PONE True
    op.drop_constraint('shift_overrides_actual_shift_pattern_id_fkey', 'shift_overrides', type_='foreignkey')
    op.drop_column('shift_overrides', 'actual_shift_pattern_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_overrides', sa.Column('actual_shift_pattern_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('shift_overrides_actual_shift_pattern_id_fkey', 'shift_overrides', 'shift_patterns', ['actual_shift_pattern_id'], ['id'])
    op.drop_column('shift_overrides', 'actual_shift_code')
    # ### end Alembic commands ###
