"""Add reference_date column to shift_assignments

Revision ID: c970f368ed81
Revises: 6c53c777fae1
Create Date: 2025-04-23 18:19:31.620697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c970f368ed81'
down_revision: Union[str, None] = '6c53c777fae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_assignments', sa.Column('reference_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift_assignments', 'reference_date')
    # ### end Alembic commands ###
