"""Add shift patterns, assignments, and absences tables

Revision ID: ecf598d45ac8
Revises: 7fd98f1e6772
Create Date: 2025-04-23 13:17:12.846496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecf598d45ac8'
down_revision: Union[str, None] = '7fd98f1e6772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
