"""Add criticidad column to machines table

Revision ID: ed5c1cf3b32b
Revises: 9fda28593b9b
Create Date: 2025-04-21 16:38:06.501548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed5c1cf3b32b'
down_revision: Union[str, None] = '9fda28593b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.alter_column('inventory', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('lines', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('machines', sa.Column('criticidad', sa.String(length=50), nullable=True))
    op.alter_column('machines', 'modelo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('machines', 'marca',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('machines', 'numero_serie',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('machines', 'line_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('machines', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.alter_column('maintenances', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_maintenances_id'), 'maintenances', ['id'], unique=False)
    op.create_foreign_key(None, 'maintenances', 'work_orders', ['generated_order_id'], ['id'])
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_sections_id'), 'sections', ['id'], unique=False)
    op.create_unique_constraint(None, 'sections', ['nombre'])
    op.alter_column('supplier_product_prices', 'product_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Nombre del producto ofrecido.',
               existing_nullable=False)
    op.alter_column('supplier_product_prices', 'supplier_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID del proveedor que ofrece el precio.',
               existing_nullable=False)
    op.alter_column('supplier_product_prices', 'warehouse_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID del almacén asociado a esta oferta (ej: entrega habitual). Opcional.',
               existing_nullable=True)
    op.alter_column('supplier_product_prices', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Precio unitario ofrecido por el proveedor.',
               existing_nullable=False)
    op.alter_column('supplier_product_prices', 'discount',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               comment=None,
               existing_comment='Porcentaje de descuento ofrecido (0-100).',
               existing_server_default=sa.text('0.0'))
    op.alter_column('supplier_product_prices', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora de la última actualización de esta oferta.',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_spp_product_name', table_name='supplier_product_prices')
    op.drop_index('idx_spp_supplier_id', table_name='supplier_product_prices')
    op.create_index(op.f('ix_supplier_product_prices_id'), 'supplier_product_prices', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_product_prices_product_name'), 'supplier_product_prices', ['product_name'], unique=False)
    op.create_index(op.f('ix_supplier_product_prices_supplier_id'), 'supplier_product_prices', ['supplier_id'], unique=False)
    op.drop_constraint('fk_supplier', 'supplier_product_prices', type_='foreignkey')
    op.drop_constraint('fk_warehouse', 'supplier_product_prices', type_='foreignkey')
    op.create_foreign_key(None, 'supplier_product_prices', 'suppliers', ['supplier_id'], ['id'])
    op.create_foreign_key(None, 'supplier_product_prices', 'warehouses', ['warehouse_id'], ['id'])
    op.drop_table_comment(
        'supplier_product_prices',
        existing_comment='Almacena precios ofrecidos por proveedores para productos específicos, usado para comparación.',
        schema=None
    )
    op.alter_column('suppliers', 'company',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('suppliers', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_unique_constraint(None, 'warehouses', ['name'])
    op.create_index(op.f('ix_work_orders_id'), 'work_orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_id'), table_name='work_orders')
    op.drop_constraint(None, 'warehouses', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.alter_column('suppliers', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('suppliers', 'company',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_table_comment(
        'supplier_product_prices',
        'Almacena precios ofrecidos por proveedores para productos específicos, usado para comparación.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'supplier_product_prices', type_='foreignkey')
    op.drop_constraint(None, 'supplier_product_prices', type_='foreignkey')
    op.create_foreign_key('fk_warehouse', 'supplier_product_prices', 'warehouses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_supplier', 'supplier_product_prices', 'suppliers', ['supplier_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_supplier_product_prices_supplier_id'), table_name='supplier_product_prices')
    op.drop_index(op.f('ix_supplier_product_prices_product_name'), table_name='supplier_product_prices')
    op.drop_index(op.f('ix_supplier_product_prices_id'), table_name='supplier_product_prices')
    op.create_index('idx_spp_supplier_id', 'supplier_product_prices', ['supplier_id'], unique=False)
    op.create_index('idx_spp_product_name', 'supplier_product_prices', ['product_name'], unique=False)
    op.alter_column('supplier_product_prices', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de la última actualización de esta oferta.',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('supplier_product_prices', 'discount',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               comment='Porcentaje de descuento ofrecido (0-100).',
               existing_server_default=sa.text('0.0'))
    op.alter_column('supplier_product_prices', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Precio unitario ofrecido por el proveedor.',
               existing_nullable=False)
    op.alter_column('supplier_product_prices', 'warehouse_id',
               existing_type=sa.INTEGER(),
               comment='ID del almacén asociado a esta oferta (ej: entrega habitual). Opcional.',
               existing_nullable=True)
    op.alter_column('supplier_product_prices', 'supplier_id',
               existing_type=sa.INTEGER(),
               comment='ID del proveedor que ofrece el precio.',
               existing_nullable=False)
    op.alter_column('supplier_product_prices', 'product_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Nombre del producto ofrecido.',
               existing_nullable=False)
    op.drop_constraint(None, 'sections', type_='unique')
    op.drop_index(op.f('ix_sections_id'), table_name='sections')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_constraint(None, 'maintenances', type_='foreignkey')
    op.drop_index(op.f('ix_maintenances_id'), table_name='maintenances')
    op.alter_column('maintenances', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.alter_column('machines', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('machines', 'line_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('machines', 'numero_serie',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('machines', 'marca',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('machines', 'modelo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('machines', 'criticidad')
    op.alter_column('lines', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    # ### end Alembic commands ###
