// src/pages/AIPredictions.js - VERSIÓN CORREGIDA PARA MODAL
import React, { useState, useEffect } from 'react';
import {
  Card,
  Table,
  Tag,
  Button,
  Space,
  DatePicker,
  Select,
  Row,
  Col,
  Statistic,
  Progress,
  Modal,
  Typography,
  Alert,
  Tooltip,
  Badge,
  List,
  Divider,
  Timeline,
  notification,
  Spin
} from 'antd';
import {
  LineChartOutlined,
  RobotOutlined,
  ReloadOutlined,
  EyeOutlined,
  FilterOutlined,
  DownloadOutlined,
  CheckCircleOutlined,
  CloseCircleOutlined,
  ClockCircleOutlined,
  WarningOutlined,
  ToolOutlined,
  CalendarOutlined,
  TrophyOutlined,
  ThunderboltOutlined,
  PlayCircleOutlined,
  SyncOutlined
} from '@ant-design/icons';
import { api } from '../apiConfig';
import { useAuth } from '../contexts/AuthContext';

const { RangePicker } = DatePicker;
const { Option } = Select;
const { Title, Text, Paragraph } = Typography;

// ✅ FUNCIÓN PARA TRADUCIR TEXTOS COMUNES
const translateText = (text) => {
  if (!text || typeof text !== 'string') return text;
  
  const translations = {
    // Componentes comunes
    'hydraulic system': 'sistema hidráulico',
    'electrical system': 'sistema eléctrico',
    'mechanical system': 'sistema mecánico',
    'cooling system': 'sistema de refrigeración',
    'lubrication system': 'sistema de lubricación',
    'control system': 'sistema de control',
    'heating system': 'sistema de calefacción',
    'conveyor system': 'sistema de transporte',
    'motor': 'motor',
    'pump': 'bomba',
    'valve': 'válvula',
    'sensor': 'sensor',
    'belt': 'correa',
    'bearing': 'rodamiento',
    'filter': 'filtro',
    'general system': 'sistema general',
    
    // Acciones comunes
    'visual inspection': 'inspección visual',
    'preventive maintenance': 'mantenimiento preventivo',
    'replace filter': 'reemplazar filtro',
    'check oil level': 'verificar nivel de aceite',
    'lubricate bearings': 'lubricar rodamientos',
    'calibrate sensors': 'calibrar sensores',
    'clean equipment': 'limpiar equipo',
    'check electrical connections': 'verificar conexiones eléctricas',
    'inspect hydraulic system': 'inspeccionar sistema hidráulico',
    'verify operational parameters': 'verificar parámetros operacionales',
    'check temperature': 'verificar temperatura',
    'inspect cooling system': 'inspeccionar sistema de refrigeración',
    'review maintenance schedule': 'revisar programa de mantenimiento',
    'monitor vibration levels': 'monitorear niveles de vibración',
    'check belt tension': 'verificar tensión de correas',
    'inspect safety systems': 'inspeccionar sistemas de seguridad',
    
    // Frases comunes
    'requires urgent inspection': 'requiere inspección urgente',
    'schedule preventive maintenance': 'programar mantenimiento preventivo',
    'monitor closely': 'monitorear de cerca',
    'increase inspection frequency': 'aumentar frecuencia de inspección',
    'based on real historical data': 'basado en datos históricos reales',
    'fallback prediction': 'predicción de respaldo',
    'generated by AI timeout': 'generado por timeout de IA',
    'insufficient data': 'datos insuficientes'
  };
  
  let translatedText = text.toLowerCase();
  
  // Aplicar traducciones
  Object.entries(translations).forEach(([english, spanish]) => {
    const regex = new RegExp(english, 'gi');
    translatedText = translatedText.replace(regex, spanish);
  });
  
  // Capitalizar primera letra
  return translatedText.charAt(0).toUpperCase() + translatedText.slice(1);
};

// ✅ FUNCIÓN PARA PROCESAR ARRAY DE RECOMENDACIONES
const processRecommendations = (recommendations) => {
  // Si no es un array, devuelve uno vacío inmediatamente.
  if (!Array.isArray(recommendations)) {
    return [];
  }
  
  const processed = recommendations.map(rec => {
    // Si el elemento es un string, lo usamos directamente.
    if (typeof rec === 'string' && rec.trim() !== '') {
      return translateText(rec);
    }
    
    // Si es un objeto, buscamos una propiedad con texto.
    if (typeof rec === 'object' && rec !== null) {
      // Buscamos en varias claves comunes que la IA podría usar.
      const actionText = rec.action || rec.recommendation || rec.text || rec.description;
      if (typeof actionText === 'string' && actionText.trim() !== '') {
        return translateText(actionText);
      }
    }
    
    // Si no encontramos nada útil (objeto vacío, null, etc.), devolvemos null.
    return null;
  });
  
  // Filtramos todos los elementos nulos para limpiar la lista final.
  return processed.filter(item => item !== null);
};


// ✅ FUNCIÓN PARA PROCESAR COMPONENTES EN RIESGO
const processComponentsAtRisk = (components) => {
  if (!components || !Array.isArray(components)) {
    return [];
  }
  
  return components.map(comp => {
    if (typeof comp === 'string') {
      return translateText(comp);
    } else if (typeof comp === 'object' && comp.name) {
      return translateText(comp.name);
    }
    return String(comp);
  });
};

// Función helper para mostrar tiempo relativo
const timeAgo = (date) => {
  const now = new Date();
  const diff = now - new Date(date);
  const minutes = Math.floor(diff / 60000);
  
  if (minutes < 1) return 'ahora mismo';
  if (minutes < 60) return `hace ${minutes} min`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `hace ${hours} h`;
  const days = Math.floor(hours / 24);
  return `hace ${days} días`;
};

const AIPredictions = () => {
  const [predictions, setPredictions] = useState([]);
  const [realMachineAnalysis, setRealMachineAnalysis] = useState([]);
  const [loading, setLoading] = useState(true);
  const [batchLoading, setBatchLoading] = useState(false);
  const [stats, setStats] = useState({});
  const [plantOverview, setPlantOverview] = useState(null);
  const [aiConfig, setAiConfig] = useState(null);
  const [selectedMachine, setSelectedMachine] = useState(null);
  const [modalVisible, setModalVisible] = useState(false);
  const [filters, setFilters] = useState({
    sectionId: null,
    riskLevel: null,
    dateRange: null
  });
  
  const { currentUser } = useAuth();

  useEffect(() => {
    loadAIConfiguration();
    loadRealData();
  }, [filters]);

  const loadAIConfiguration = async () => {
    try {
      const response = await api.get('/ai/configuration');
      const config = response.data.configuration;
      setAiConfig(config);
      console.log('🤖 Configuración IA cargada:', config);
    } catch (error) {
      console.error('Error cargando configuración IA:', error);
      setAiConfig({
        default_prediction_model: 'qwen3.5:9b-q4_K_M',
        default_chat_model: 'gemma4:12b-it-qat',
        prediction_confidence_threshold: 70
      });
    }
  };

  const loadRealData = async () => {
    try {
      setLoading(true);
      
      const [overviewRes, realPredictionsRes] = await Promise.all([
        api.get('/ai/plant-overview'),
        api.get('/ai/predictions/real-data')
      ]);

      setPlantOverview(overviewRes.data);
      
      const realPredictions = realPredictionsRes.data.predictions || [];
      setPredictions(realPredictions);
      
      const totalPredictions = realPredictions.length;
      const correctPredictions = realPredictions.filter(p => p.actual_outcome === 'correct').length;
      const accuracyRate = totalPredictions > 0 ? (correctPredictions / totalPredictions * 100) : 0;
      
      setStats({
        total_predictions: totalPredictions,
        correct_predictions: correctPredictions,
        accuracy_rate: accuracyRate,
        pending_validation: realPredictions.filter(p => !p.actual_outcome).length
      });

      await loadProblematicMachines(overviewRes.data);
      
      console.log('📊 Datos reales cargados:', {
        predictions: realPredictions.length,
        plantData: overviewRes.data
      });
      
    } catch (error) {
      console.error('Error cargando datos reales:', error);
      notification.error({
        message: 'Error cargando datos',
        description: 'No se pudieron cargar las predicciones. Revisa la conexión.'
      });
    } finally {
      setLoading(false);
    }
  };

  const loadProblematicMachines = async (plantData) => {
    try {
      const machines = plantData?.top_problematic_machines || [];
      
      const analysisPromises = machines.slice(0, 5).map(async (machine) => {
        try {
          const machineId = machine.id;
          
          if (!machineId || machineId === 'undefined') {
            console.warn(`🚨 Máquina sin ID válido:`, machine);
            return null;
          }
          
          console.log(`🔍 Analizando máquina ID: ${machineId} (${machine.nombre})`);
          
          const response = await api.get(`/ai/machine-analysis/${machineId}`);
          return response.data;
        } catch (error) {
          console.error(`Error analizando máquina ${machine.nombre}:`, error);
          return null;
        }
      });

      const analysisResults = await Promise.all(analysisPromises);
      const validAnalysis = analysisResults.filter(analysis => analysis !== null);
      
      setRealMachineAnalysis(validAnalysis);
    } catch (error) {
      console.error('Error cargando análisis de máquinas:', error);
    }
  };

  const generateRealPrediction = async (machineId) => {
    try {
      if (!machineId || machineId === 'undefined') {
        Modal.error({
          title: 'Error',
          content: 'ID de máquina no válido. No se puede generar predicción.'
        });
        return;
      }
      
      console.log(`🔮 Generando predicción para máquina ID: ${machineId}`);
      setLoading(true);
      
      const modelToUse = aiConfig?.default_prediction_model;
      const confidenceThreshold = aiConfig?.prediction_confidence_threshold || 70;
      
      console.log(`🤖 Usando modelo: ${modelToUse || 'detección automática'}, Umbral: ${confidenceThreshold}%`);
      
      const payload = {
        days_ahead: 30,
        confidence_threshold: confidenceThreshold
      };
      if (modelToUse) {
        payload.model_override = modelToUse;
      }

      const response = await api.post(`/ai/predict-maintenance/${machineId}`, payload);
      
      Modal.success({
        title: '✅ Predicción Generada con Datos Reales',
        content: (
          <div>
            <p><strong>Máquina:</strong> {response.data.machine_name}</p>
            <p><strong>Modelo IA usado:</strong> {response.data.prediction_analysis?.model_used || modelToUse}</p>
            <p><strong>Fecha estimada:</strong> {response.data.prediction_analysis?.estimated_date || 'N/A'}</p>
            <p><strong>Confianza:</strong> {response.data.prediction_analysis?.prediction_confidence || 0}%</p>
            <p><strong>Nivel de riesgo:</strong> {response.data.prediction_analysis?.risk_level || 'medio'}</p>
            <p><strong>Fallos históricos:</strong> {response.data.historical_context?.total_failures || 0}</p>
          </div>
        ),
        onOk: () => {
          loadRealData();
        }
      });
    } catch (error) {
      console.error(`Error generando predicción para máquina ${machineId}:`, error);
      Modal.error({
        title: 'Error en Predicción',
        content: `No se pudo generar la predicción: ${error.response?.data?.detail || error.message}`
      });
    } finally {
      setLoading(false);
    }
  };

  const triggerBatchPredictions = async () => {
    try {
      setBatchLoading(true);
      
      const response = await api.post('/ai/predictions/trigger-batch', {
        section_id: filters.sectionId,
        force_refresh: true
      });
      
      notification.success({
        message: 'Predicciones en Lote Iniciadas',
        description: response.data.message,
        duration: 5
      });
      
      setTimeout(() => {
        loadRealData();
      }, 5000);
      setTimeout(() => {
        loadRealData();
      }, 20000);
      
    } catch (error) {
      console.error('Error en predicciones en lote:', error);
      notification.error({
        message: 'Error',
        description: error.response?.data?.detail || 'No se pudieron iniciar las predicciones en lote'
      });
    } finally {
      setBatchLoading(false);
    }
  };

  const columns = [
    {
      title: 'Máquina Real',
      dataIndex: ['machine', 'name'],
      key: 'machine',
      render: (text, record) => (
        <div>
          <strong>{text || record.machine?.name || 'N/A'}</strong>
          <br />
          <Text type="secondary">{record.machine?.section || 'N/A'}</Text>
        </div>
      )
    },
    {
      title: 'Modelo de IA',
      dataIndex: 'model_used',
      key: 'model',
      render: (model, record) => {
        const actualModel = model || aiConfig?.default_prediction_model || 'IA GMAO';
        const isConfigured = model === aiConfig?.default_prediction_model;
        
        return (
          <Space direction="vertical" size="small">
            <Tag color={isConfigured ? "green" : "blue"}>
              <RobotOutlined /> {actualModel}
            </Tag>
            <Text style={{ fontSize: '11px' }}>
              {record.data_source === 'ai_prediction_real' ? 
                '✅ Predicción IA real' : 
                '📊 Análisis histórico'}
            </Text>
          </Space>
        );
      }
    },
    {
      title: 'Probabilidad Real',
      dataIndex: 'probability',
      key: 'probability',
      render: (prob, record) => (
        <Space direction="vertical" size="small">
          <Progress 
            percent={Math.round(prob || 0)} 
            size="small"
            status={prob > 80 ? 'exception' : prob > 60 ? 'active' : 'success'}
            format={(percent) => `${percent}%`}
          />
          <Text style={{ fontSize: '11px' }}>
            {record.real_failures_count ? 
              `${record.real_failures_count} fallos históricos` : 
              `Confianza: ${record.confidence || 0}%`}
          </Text>
        </Space>
      )
    },
    {
      title: 'Predicción',
      dataIndex: 'predicted_date',
      key: 'prediction',
      render: (date, record) => {
        if (!date) return <Text type="secondary">Sin fecha</Text>;
        
        const predDate = new Date(date);
        const daysUntil = Math.ceil((predDate - new Date()) / (1000 * 60 * 60 * 24));
        
        return (
          <Space direction="vertical" size="small">
            <Text strong>{predDate.toLocaleDateString()}</Text>
            <Tag color={daysUntil <= 7 ? "red" : daysUntil <= 30 ? "orange" : "green"} size="small">
              <ClockCircleOutlined /> 
              {daysUntil > 0 ? `${daysUntil} días` : 'Vencido'}
            </Tag>
          </Space>
        );
      }
    },
    {
      title: 'Estado / Validación',
      dataIndex: 'status',
      key: 'status',
      render: (status, record) => {
        if (record.actual_outcome) {
          const config = {
            'correct': { color: 'success', icon: <CheckCircleOutlined />, text: '✅ Correcto' },
            'false_positive': { color: 'warning', icon: <CloseCircleOutlined />, text: '⚠️ Falso positivo' },
            'false_negative': { color: 'error', icon: <CloseCircleOutlined />, text: '❌ Falso negativo' }
          };
          
          const item = config[record.actual_outcome] || { color: 'default', text: record.actual_outcome };
          return (
            <Tag color={item.color} icon={item.icon}>
              {item.text}
            </Tag>
          );
        }
        
        const statusConfig = {
          'active': { color: 'processing', text: '🔄 Activa' },
          'synthetic': { color: 'default', text: '📊 Análisis histórico' },
          'ai_prediction_real': { color: 'success', text: '🤖 IA Real' }
        };
        
        const currentStatus = record.data_source || status || 'active';
        const statusItem = statusConfig[currentStatus] || { color: 'default', text: currentStatus };
        
        return <Tag color={statusItem.color}>{statusItem.text}</Tag>;
      }
    },
    {
      title: 'Acciones',
      key: 'actions',
      render: (_, record) => (
        <Space>
          <Button
            size="small"
            icon={<EyeOutlined />}
            onClick={() => {
              setSelectedMachine(record);
              setModalVisible(true);
            }}
          >
            Ver Detalles
          </Button>
          <Button
            size="small"
            icon={<ReloadOutlined />}
            onClick={() => {
              const machineId = record.machine?.id;
              if (machineId && machineId !== 'undefined') {
                generateRealPrediction(machineId);
              } else {
                notification.error({
                  message: 'Error',
                  description: `No se puede analizar la máquina: ID no válido`
                });
              }
            }}
            disabled={!record.machine?.id}
            loading={loading}
          >
            Actualizar
          </Button>
        </Space>
      )
    }
  ];

  return (
    <div>
      {/* Header con datos reales de tu planta */}
      <Card style={{ marginBottom: 24 }}>
        <Row justify="space-between" align="middle">
          <Col>
            <Title level={2} style={{ margin: 0 }}>
              <LineChartOutlined style={{ marginRight: 8, color: '#1890ff' }} />
              Predicciones IA - Datos Reales de tu Planta
            </Title>
            <Text type="secondary">
              Análisis predictivo basado en {plantOverview?.plant_overview?.ordenes_ultimo_mes || 0} órdenes reales del último mes
            </Text>
          </Col>
          <Col>
            <Space>
              <Select
                placeholder="Filtrar por sección"
                style={{ width: 180 }}
                allowClear
                value={filters.sectionId}
                onChange={(value) => setFilters(prev => ({ ...prev, sectionId: value }))}
              >
                <Option value={1}>Prensas</Option>
                <Option value={2}>Mantenimiento</Option>
                <Option value={4}>Esmaltadoras</Option>
                <Option value={5}>Clasificacion</Option>
                <Option value={6}>RECTIFICADORAS</Option>
                <Option value={7}>Hornos</Option>
                <Option value={8}>Diseño</Option>
              </Select>
              
              <Button 
                icon={<PlayCircleOutlined />}
                onClick={triggerBatchPredictions}
                loading={batchLoading}
                type="primary"
                ghost
              >
                Generar Lote
              </Button>
              
              <Button 
                icon={<DownloadOutlined />}
                onClick={() => {
                  const csvContent = "data:text/csv;charset=utf-8," 
                    + "Máquina,Sección,Modelo,Probabilidad,Fecha Predicha,Estado\n"
                    + predictions.map(p => 
                        `${p.machine?.name || 'N/A'},${p.machine?.section || 'N/A'},${p.model_used || 'N/A'},${p.probability || 0},${p.predicted_date || 'N/A'},${p.status || 'N/A'}`
                      ).join("\n");
                  
                  const link = document.createElement("a");
                  link.setAttribute("href", encodeURI(csvContent));
                  link.setAttribute("download", `predicciones_ia_${new Date().toISOString().split('T')[0]}.csv`);
                  document.body.appendChild(link);
                  link.click();
                  document.body.removeChild(link);
                }}
              >
                Exportar CSV
              </Button>
              
              <Button 
                type="primary" 
                icon={<ReloadOutlined />}
                onClick={loadRealData}
                loading={loading}
              >
                Actualizar Todo
              </Button>
            </Space>
          </Col>
        </Row>

        <Alert
          message={
            <Space>
              <RobotOutlined />
              <span>Configuración IA Activa:</span>
              <Tag color="blue">{aiConfig?.default_prediction_model || 'Cargando...'}</Tag>
              <span>• Umbral: {aiConfig?.prediction_confidence_threshold || 70}%</span>
            </Space>
          }
          type="info"
          showIcon={false}
          style={{ marginTop: 16 }}
        />
      </Card>

      {/* Estadísticas REALES de tu planta */}
      <Row gutter={16} style={{ marginBottom: 24 }}>
        <Col xs={24} sm={6}>
          <Card>
            <Statistic
              title="Máquinas Monitoreadas"
              value={plantOverview?.plant_overview?.total_maquinas || 0}
              prefix={<RobotOutlined />}
              suffix="reales"
            />
            <Text type="secondary" style={{ fontSize: '11px' }}>
              {plantOverview?.plant_overview?.total_secciones || 7} secciones
            </Text>
          </Card>
        </Col>
        <Col xs={24} sm={6}>
          <Card>
            <Statistic
              title="Predicciones Totales"
              value={stats.total_predictions || 0}
              prefix={<LineChartOutlined />}
              suffix="generadas"
            />
            <Text type="secondary" style={{ fontSize: '11px' }}>
              {stats.pending_validation || 0} pendientes validación
            </Text>
          </Card>
        </Col>
        <Col xs={24} sm={6}>
          <Card>
            <Statistic
              title="Precisión IA Real"
              value={stats.accuracy_rate || 0}
              suffix="%"
              precision={1}
              valueStyle={{ color: stats.accuracy_rate > 75 ? '#3f8600' : '#cf1322' }}
              prefix={<TrophyOutlined />}
            />
            <Text type="secondary" style={{ fontSize: '11px' }}>
              {stats.correct_predictions || 0} de {stats.total_predictions || 0} correctas
            </Text>
          </Card>
        </Col>
        <Col xs={24} sm={6}>
          <Card>
            <Statistic
              title="% Correctivo Planta"
              value={plantOverview?.plant_overview?.porcentaje_correctivo_planta || 0}
              suffix="%"
              precision={1}
              prefix={<ToolOutlined />}
              valueStyle={{ 
                color: (plantOverview?.plant_overview?.porcentaje_correctivo_planta || 0) > 60 ? 
                  '#cf1322' : '#3f8600' 
              }}
            />
            <Text type="secondary" style={{ fontSize: '11px' }}>
              {plantOverview?.plant_overview?.fallos_ultimo_mes || 0} fallos último mes
            </Text>
          </Card>
        </Col>
      </Row>

      {/* Alertas basadas en TUS datos reales */}
      {plantOverview?.top_problematic_machines?.length > 0 && (
        <Alert
          message="🚨 Máquinas de TU planta que requieren atención urgente"
          description={
            <div style={{ marginTop: 8 }}>
              {plantOverview.top_problematic_machines.slice(0, 3).map(machine => (
                <Tag key={machine.nombre} color="red" style={{ marginBottom: 4 }}>
                  {machine.nombre} ({machine.seccion}): {machine.fallos} fallos reales
                </Tag>
              ))}
              <div style={{ marginTop: 8, fontSize: '12px', color: '#666' }}>
                Modelo configurado: <strong>{aiConfig?.default_prediction_model || 'Cargando...'}</strong>
              </div>
            </div>
          }
          type="error"
          showIcon
          style={{ marginBottom: 24 }}
          action={
            <Button 
              size="small" 
              onClick={triggerBatchPredictions}
              loading={batchLoading}
              icon={<ThunderboltOutlined />}
            >
              Analizar Todas
            </Button>
          }
        />
      )}

      {/* Contenido principal */}
      <Row gutter={16}>
        <Col xs={24} lg={16}>
          <Card 
            title={
              <Space>
                <RobotOutlined />
                Predicciones Basadas en Datos Reales
                {loading && <Spin size="small" />}
              </Space>
            }
            extra={
              <Space>
                <Tag color="green">Total: {predictions.length}</Tag>
                <Button 
                  size="small" 
                  icon={<SyncOutlined />}
                  onClick={loadRealData}
                  loading={loading}
                >
                  Refrescar
                </Button>
              </Space>
            }
          >
            <Table
              columns={columns}
              dataSource={predictions}
              loading={loading}
              rowKey={(record) => record.id || `synthetic_${record.machine?.id}`}
              pagination={{
                pageSize: 10,
                showSizeChanger: true,
                showQuickJumper: true,
                showTotal: (total) => `${total} predicciones de TU planta`
              }}
              locale={{
                emptyText: (
                  <div style={{ padding: '20px', textAlign: 'center' }}>
                    <RobotOutlined style={{ fontSize: '48px', color: '#d9d9d9' }} />
                    <div style={{ marginTop: 16 }}>
                      <Text type="secondary">No hay predicciones generadas</Text>
                      <br />
                      <Button 
                        type="primary" 
                        onClick={triggerBatchPredictions}
                        loading={batchLoading}
                        style={{ marginTop: 8 }}
                      >
                        Generar Predicciones
                      </Button>
                    </div>
                  </div>
                )
              }}
            />
          </Card>
        </Col>

        <Col xs={24} lg={8}>
          <Card title="Análisis en Tiempo Real" extra={<CalendarOutlined />}>
            <Timeline>
              {realMachineAnalysis.slice(0, 5).map((analysis, index) => (
                <Timeline.Item
                  key={index}
                  color={
                    analysis.failure_analysis?.nivel_riesgo === 'alto' ? 'red' :
                    analysis.failure_analysis?.nivel_riesgo === 'medio' ? 'orange' : 'green'
                  }
                  dot={
                    analysis.failure_analysis?.nivel_riesgo === 'alto' ? 
                      <WarningOutlined style={{ color: 'red' }} /> : 
                      <CheckCircleOutlined />
                  }
                >
                  <div>
                    <Text strong>{analysis.machine_info?.nombre}</Text>
                    <br />
                    <Text type="secondary" style={{ fontSize: '12px' }}>
                      {analysis.failure_analysis?.total_fallos} fallos • 
                      MTBF: {analysis.failure_analysis?.mtbf_dias?.toFixed(1) || 'N/A'} días
                    </Text>
                    <br />
                    <Tag size="small" color={
                      analysis.failure_analysis?.nivel_riesgo === 'alto' ? 'red' :
                      analysis.failure_analysis?.nivel_riesgo === 'medio' ? 'orange' : 'green'
                    }>
                      {analysis.failure_analysis?.nivel_riesgo} riesgo
                    </Tag>
                  </div>
                </Timeline.Item>
              ))}
            </Timeline>
            
            <Button 
              type="link" 
              onClick={() => window.location.href = '/ai-dashboard'}
              style={{ padding: 0 }}
            >
              Ver dashboard completo →
            </Button>
          </Card>
        </Col>
      </Row>

      {/* ✅ MODAL CORREGIDO - TEXTO HORIZONTAL Y EN ESPAÑOL */}
      <Modal
        title={`Análisis Real - ${selectedMachine?.machine?.name || 'N/A'}`}
        visible={modalVisible}
        onCancel={() => setModalVisible(false)}
        footer={[
          <Button key="close" onClick={() => setModalVisible(false)}>
            Cerrar
          </Button>,
          <Button 
            key="update" 
            type="primary"
            icon={<ReloadOutlined />}
            onClick={() => {
              if (selectedMachine?.machine?.id) {
                generateRealPrediction(selectedMachine.machine.id);
                setModalVisible(false);
              }
            }}
            disabled={!selectedMachine?.machine?.id}
          >
            Generar Nueva Predicción
          </Button>
        ]}
        width={800}
        style={{ maxHeight: '80vh' }}
      >
        {selectedMachine && (
          <div style={{ maxHeight: '60vh', overflowY: 'auto' }}>
            <Divider orientation="left">Datos Reales de tu Planta</Divider>
            <Row gutter={16}>
              <Col span={12}>
                <Text strong>Máquina:</Text> {selectedMachine.machine?.name}<br />
                <Text strong>Sección:</Text> {selectedMachine.machine?.section}<br />
                <Text strong>Modelo usado:</Text> {selectedMachine.model_used || aiConfig?.default_prediction_model}
              </Col>
              <Col span={12}>
                <Text strong>Probabilidad:</Text> {selectedMachine.probability || 0}%<br />
                <Text strong>Confianza:</Text> {selectedMachine.confidence || 0}%<br />
                <Text strong>Fecha predicha:</Text> {selectedMachine.predicted_date ? 
                  new Date(selectedMachine.predicted_date).toLocaleDateString() : 'N/A'}
              </Col>
            </Row>

            {/* ✅ COMPONENTES EN RIESGO - CORREGIDO */}
            {selectedMachine.components_at_risk && selectedMachine.components_at_risk.length > 0 && (
              <>
                <Divider orientation="left">Componentes en Riesgo</Divider>
                <div style={{ marginBottom: 16 }}>
                  {processComponentsAtRisk(selectedMachine.components_at_risk).map((component, idx) => (
                    <Tag key={idx} color="orange" style={{ marginBottom: 4, marginRight: 4 }}>
                      {component}
                    </Tag>
                  ))}
                </div>
              </>
            )}

            {(() => {
      // 1. PRIMERO, procesamos las acciones y guardamos el resultado limpio.
      const processedActions = processRecommendations(selectedMachine.recommended_actions);

      // 2. LUEGO, decidimos si mostrar la sección basándonos en el resultado LIMPIO.
      if (processedActions && processedActions.length > 0) {
        return (
          <>
            <Divider orientation="left">Acciones Recomendadas</Divider>
            <List
              size="small"
              // 3. FINÁLMENTE, pasamos los datos ya limpios a la lista.
              dataSource={processedActions}
              renderItem={(action, index) => (
                <List.Item style={{ padding: '8px 0', borderBottom: '1px solid #f0f0f0' }}>
                  <Space align="start">
                    <Badge count={index + 1} size="small" />
                    <Text style={{ 
                      wordBreak: 'break-word',
                      whiteSpace: 'normal',
                      lineHeight: '1.4'
                    }}>
                      {action}
                    </Text>
                  </Space>
                </List.Item>
              )}
              style={{ 
                background: '#fafafa', 
                padding: '12px',
                borderRadius: '6px',
                marginBottom: '16px'
              }}
            />
          </>
        );
      }

      // Si no hay acciones válidas que mostrar, no se renderiza nada.
      return null;
    })()}

            {/* ✅ ANÁLISIS ADICIONAL SI EXISTE */}
            {selectedMachine.prediction_data && (
              <>
                <Divider orientation="left">Análisis Detallado</Divider>
                <Row gutter={16}>
                  <Col span={12}>
                    <Text strong>Tipo de fallo:</Text> 
                    <Text style={{ marginLeft: 8 }}>
                      {translateText(selectedMachine.prediction_data.failure_type || 'general')}
                    </Text>
                    <br />
                    <Text strong>Severidad:</Text> 
                    <Tag color={
                      selectedMachine.prediction_data.severity === 'critical' ? 'red' :
                      selectedMachine.prediction_data.severity === 'high' ? 'orange' :
                      selectedMachine.prediction_data.severity === 'medium' ? 'yellow' : 'green'
                    } style={{ marginLeft: 8 }}>
                      {selectedMachine.prediction_data.severity === 'critical' ? 'Crítica' :
                       selectedMachine.prediction_data.severity === 'high' ? 'Alta' :
                       selectedMachine.prediction_data.severity === 'medium' ? 'Media' : 'Baja'}
                    </Tag>
                  </Col>
                  <Col span={12}>
                    <Text strong>Días hasta fallo:</Text> 
                    <Text style={{ marginLeft: 8 }}>
                      {selectedMachine.prediction_data.days_until_failure || 'N/A'} días
                    </Text>
                    <br />
                    <Text strong>Datos utilizados:</Text> 
                    <Text style={{ marginLeft: 8 }}>
                      {selectedMachine.data_points_used || 0} registros históricos
                    </Text>
                  </Col>
                </Row>
              </>
            )}

            <Divider orientation="left">Información del Análisis</Divider>
            <Row gutter={16}>
              <Col span={12}>
                <Text strong>Fuente de datos:</Text> 
                <Tag color="blue" style={{ marginLeft: 8 }}>
                  {selectedMachine.data_source === 'ai_prediction_real' ? 
                    '🤖 IA Real' : 
                    selectedMachine.data_source === '100_percent_real_ai_prediction' ?
                    '🎯 Predicción IA Verificada' :
                    '📊 Análisis histórico'}
                </Tag>
              </Col>
              <Col span={12}>
                <Text strong>Creado:</Text> 
                <Text style={{ marginLeft: 8 }}>
                  {selectedMachine.created_at ? 
                    new Date(selectedMachine.created_at).toLocaleDateString() + ' ' +
                    new Date(selectedMachine.created_at).toLocaleTimeString() : 
                    'N/A'}
                </Text>
              </Col>
            </Row>
            
            {/* ✅ RESUMEN EN ESPAÑOL */}
            <Alert
              message="Resumen del Análisis"
              description={
                <div style={{ marginTop: 8 }}>
                  <Text>
                    Esta predicción se basa en los datos reales de tu planta industrial: 
                    historial de órdenes de trabajo, patrones de fallos, cálculos de MTBF reales 
                    y comparación con máquinas similares de tu instalación.
                  </Text>
                  <br /><br />
                  <Text strong>
                    Modelo utilizado: {selectedMachine.model_used || aiConfig?.default_prediction_model}
                  </Text>
                  <br />
                  <Text strong>
                    Umbral de confianza: {aiConfig?.prediction_confidence_threshold || 70}%
                  </Text>
                  <br />
                  <Text strong>
                    Estado: {selectedMachine.status === 'active' ? 'Activa' : 
                             selectedMachine.status === 'validated' ? 'Validada' : 
                             selectedMachine.status}
                  </Text>
                </div>
              }
              type="info"
              showIcon
              style={{ marginTop: 16 }}
            />
          </div>
        )}
      </Modal>
    </div>
  );
};

export default AIPredictions;